spring:
    datasource:
        url: jdbc:oracle:thin:@SEOCDSPRDS001.paulista.local:1521/PDB191
        username: multiconcsitefwebclient3_web
        password: multiconcsitefwebclient3_web
logging:
    level:
        org.springframework.security: DEBUG
